#!/bin/sh

# Generate built-in huge random data for encryption

[ -z "$1" ] && echo "Use: $0 <filename> <size>" && exit 1
[ -r $1 ] && echo "WARNING: $1 already present, exiting" && exit

# Data size
[ -z "$2" ] && SIZE=8192 || SIZE=$2

# C preprocessor guard
F=$(basename $1)
FP=$(printf $F | tr ".-" "__")
GUARD_NAME=$(printf $FP | tr "[:lower:]" "[:upper:]")
ARRAY_NAME=$(printf $FP | tr "[:upper:]" "[:lower:]")

(cat > $1) << EOF
#ifndef _${GUARD_NAME}_
#define _${GUARD_NAME}_

/*
 * This is autogenerated file - see crypto-prepare.sh
 */

#define ${GUARD_NAME}_ARRAY_SIZE $SIZE
unsigned char ${ARRAY_NAME}_array[${GUARD_NAME}_ARRAY_SIZE] = {
EOF
dd if=/dev/urandom bs=$SIZE count=1 status=none | xxd -i >> $1

(cat >> $1) << EOF
};
#endif /* _${GUARD_NAME}_ */

EOF
